module.exports = {
    'eyes': ':eyes::earth_americas:',
    'darkstar': ':milky_way:',
    'gdtrfb': ':red_car::dash::disappointed:',
    'catfishjohn': ':cat::fish::toilet:',
    'caseyjones': ':train2::snowflake:',
    'loveeachother': ':man::heart::woman:',
    'chinacatsunflower': ':cn::cat::sunflower:',
    'hesgone': ':runner::dash:',
    'crazyfingers': ':stuck_out_tongue_winking_eye::hand:',
    'rowjimmy': ':rowboat:',
    'usblues': ':us::jeans:',
    'musicneverstopped': ':musical_note::no_entry_sign::busstop:',
    'stellablue': ':woman::jeans:',
    'thewheel': ':ferris_wheel:',
    'letitgrow': ':baby::boy::man:',
    'chinatownshuffle': ':cn::dancers:',
    'goodlovin': ':heart::+1:',
    'terrapin': ':turtle::station:',
    'lookslikerain': ':eyes::umbrella:',
    'morningdew': ':sunrise::droplet:',
    'looselucy': ':open_hands::woman:',
    'fire': ':fire::mount_fuji:',
    'wharfrat': ':bridge_at_night::rat:',
    'truckin': ':truck::dash:',
    'candyman': ':candy::man:',
    'kingbee': ':crown::honeybee:',
    'ragingwun': ':eyes:',
    'hightime': ':herb::alarm_clock:',
    'hsf': ':ambulance::dash: → :curly_loop: → :man::tokyo_tower:',
    'wrs': ':sunny::umbrella::cloud::snowflake::pencil::chart_with_upwards_trend:',
    'dancin': ':dancers::office::post_office::love_hotel::department_store:',
    'coldrainandsnow': ':umbrella::snowflake:',
    'default': 'Emoji not found! :p'
};
